# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectfive.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_otherWindow5(object):
    def setupUi(self, otherWindow5):
        otherWindow5.setObjectName("otherWindow5")
        otherWindow5.resize(550, 487)
        self.centralwidget = QtWidgets.QWidget(otherWindow5)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 410, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        otherWindow5.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(otherWindow5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 20))
        self.menubar.setObjectName("menubar")
        otherWindow5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(otherWindow5)
        self.statusbar.setObjectName("statusbar")
        otherWindow5.setStatusBar(self.statusbar)

        self.retranslateUi(otherWindow5)
        QtCore.QMetaObject.connectSlotsByName(otherWindow5)

    def retranslateUi(self, otherWindow5):
        _translate = QtCore.QCoreApplication.translate
        otherWindow5.setWindowTitle(_translate("otherWindow5", "MainWindow"))
        self.pushButton.setText(_translate("otherWindow5", "EXIT"))
        self.label.setText(_translate("otherWindow5", "ESSAY SCORE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    otherWindow5 = QtWidgets.QMainWindow()
    ui = Ui_otherWindow5()
    ui.setupUi(otherWindow5)
    otherWindow5.show()
    sys.exit(app.exec_())
