# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectfour.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_otherWindow3(object):
    def setupUi(self, otherWindow3):
        otherWindow3.setObjectName("otherWindow3")
        otherWindow3.resize(548, 467)
        self.centralwidget = QtWidgets.QWidget(otherWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 370, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        otherWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(otherWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 20))
        self.menubar.setObjectName("menubar")
        otherWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(otherWindow3)
        self.statusbar.setObjectName("statusbar")
        otherWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(otherWindow3)
        QtCore.QMetaObject.connectSlotsByName(otherWindow3)

    def retranslateUi(self, otherWindow3):
        _translate = QtCore.QCoreApplication.translate
        otherWindow3.setWindowTitle(_translate("otherWindow3", "MainWindow"))
        self.label.setText(_translate("otherWindow3", "PLAGARISM CHECK"))
        self.pushButton.setText(_translate("otherWindow3", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    otherWindow3 = QtWidgets.QMainWindow()
    ui = Ui_otherWindow3()
    ui.setupUi(otherWindow3)
    otherWindow3.show()
    sys.exit(app.exec_())
