# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectthree.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_otherWindow2(object):
    def setupUi(self, otherWindow2):
        otherWindow2.setObjectName("otherWindow2")
        otherWindow2.resize(511, 423)
        self.centralwidget = QtWidgets.QWidget(otherWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 340, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        otherWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(otherWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 20))
        self.menubar.setObjectName("menubar")
        otherWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(otherWindow2)
        self.statusbar.setObjectName("statusbar")
        otherWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(otherWindow2)
        QtCore.QMetaObject.connectSlotsByName(otherWindow2)

    def retranslateUi(self, otherWindow2):
        _translate = QtCore.QCoreApplication.translate
        otherWindow2.setWindowTitle(_translate("otherWindow2", "MainWindow"))
        self.pushButton.setText(_translate("otherWindow2", "EXIT"))
        self.label.setText(_translate("otherWindow2", "GRAMMER CHECK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    otherWindow2 = QtWidgets.QMainWindow()
    ui = Ui_otherWindow2()
    ui.setupUi(otherWindow2)
    otherWindow2.show()
    sys.exit(app.exec_())
